Hw9
ValentynTreshchun/JavaPro pull request #10
Opened 2024-03-11 21:02 UTC by ValentynTreshchun

2024-03-12 15:32 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson7Homework9/HW9.java
> +                .orElseThrow(() -> new RuntimeException("Exception: product [type = " + type + "] not found"));
Подозреваю что это неправильный вызов Exception, но мы еще не проходили этот раздел вроде как, сделал как смогу нагуглить.

2024-03-14 15:42 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson7Homework9/HW9.java
> +                .orElseThrow(() -> new RuntimeException("Exception: product [type = " + type + "] not found"));
Исправил на NoSuchElementException

2024-03-14 15:48 UTC, ValentynTreshchun commented
Подозреваю что все методы связанные с Product стоит перенести как статические в класс Product? 
Если переносить, стоит ли распределять методы по классам соответственно типу объектов над которыми они работают?
На пример, метод GetCostByTypePriceYTD работает только с обьктами типа DiscountedProductWithDate - этот метод стоит добавить в класс Product или DiscountedProductWithDate?

2024-03-25 18:55 UTC, pipekalo requested changes

2024-03-25 18:55 UTC, pipekalo commented on src/main/java/ua/hillel/treshchun/lessons/lesson7Homework9/HW9.java
> +                        && product instanceof DiscountedProduct
в першому ж розділив умови чого ж тут так не зробив?

2024-03-25 18:55 UTC, pipekalo commented on src/main/java/ua/hillel/treshchun/lessons/lesson7Homework9/HW9.java
> +                .sorted((p1, p2) -> {
це в прниципі стандартний компаратор, можна скоротити готовим

2024-03-25 18:55 UTC, pipekalo commented on src/main/java/ua/hillel/treshchun/lessons/lesson7Homework9/HW9.java
> +                        && product.getPrice() > minPrice
розбивай на окремі

2024-03-25 18:55 UTC, pipekalo commented on src/main/java/ua/hillel/treshchun/lessons/lesson7Homework9/HW9.java
> +    private Map<String, List<Product>> GroupByType(List<Product> products) {
тут решение в 2 строчки, погугли лучше)

2024-03-29 15:42 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson7Homework9/HW9.java
> +                        && product instanceof DiscountedProduct
недодивився код мабуть, виправив

2024-03-29 16:10 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson7Homework9/HW9.java
> +                .sorted((p1, p2) -> {
Це був мій перший компаратор :) 
Замінив з використанням LocalDateTime.compareTo()

2024-03-29 16:12 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson7Homework9/HW9.java
> +                        && product.getPrice() > minPrice
розбив

2024-03-31 18:56 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson7Homework9/HW9.java
> +    private Map<String, List<Product>> GroupByType(List<Product> products) {
заменил с использованием Map.computeIfAbsent()
это какой-то читинг :)

2024-04-03 10:43 UTC, merged