Hw6
ValentynTreshchun/JavaPro pull request #7
Opened 2024-02-26 13:39 UTC by ValentynTreshchun

HW6 ready

2024-02-26 15:39 UTC, pipekalo requested changes

2024-02-26 15:39 UTC, pipekalo commented on src/main/java/ua/hillel/treshchun/lessons/lesson4Homework6/Obstacle.java
> +    boolean overcome(Participant participant);
Ох уже эти препятсвия что преодолевают участников)

2024-02-26 15:39 UTC, pipekalo commented on src/main/java/ua/hillel/treshchun/lessons/lesson4Homework6/ObstacleImpl/Treadmill.java
> +    public boolean overcome(Participant participant) {
Ну я думаю ты и сам видишь идентичность данных методов) Хотя их надо бы согласно комменту выше слегка в другое место переместить

2024-02-26 15:39 UTC, pipekalo commented on src/main/java/ua/hillel/treshchun/lessons/lesson4Homework6/ParticipantImpl/Participant.java
> +public abstract class Participant {
тут нужно немного переделать что бы именно участник мог преодолевать препядствия

2024-02-27 19:13 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson4Homework6/ObstacleImpl/Obstacle.java
> +    protected Obstacle() {
конструктор Protected щоб заборонити створення перешкоди невизначеного типу.

2024-02-27 19:14 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson4Homework6/ParticipantImpl/Participant.java
> +public abstract class Participant {
змінив

2024-03-07 21:00 UTC, pipekalo approved these changes

2024-03-07 21:00 UTC, pipekalo commented on src/main/java/ua/hillel/treshchun/lessons/lesson4Homework6/ObstacleImpl/Obstacle.java
> +    protected Obstacle() {
Краще просто ставити Abstract слово, теж саме але очевидніше

2024-03-11 21:11 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson4Homework6/ObstacleImpl/Obstacle.java
> +    protected Obstacle() {
Точно, спасибо! Исправил.

2024-03-11 21:30 UTC, merged