Wh7
ValentynTreshchun/JavaPro pull request #8
Opened 2024-03-03 20:34 UTC by ValentynTreshchun

2024-03-11 18:47 UTC, pipekalo requested changes

2024-03-14 15:13 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson5Homework7/HW7.java
> +        while (iter1.hasNext()) {
повидаляв зайві змінні де можливо

2024-03-14 15:13 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson5Homework7/HW7.java
> +        System.out.println(inputList);
сделал

2024-03-14 15:18 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson5Homework7/Occurance.java
> +                if (word.equals(uniqueWord)) {
Касательно использования final/effectively final, тут решение понятно - использование свойства на уровне обьекта с которым я работаю.

2024-03-14 15:19 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson5Homework7/Occurance.java
>      public static List<Occurance> findOccurance(List<String> inputList) {
я пропустил эту часть задания в прошлый раз - 4. *** 
Добавил в этой перездаче

2024-03-14 15:23 UTC, ValentynTreshchun commented on src/main/java/ua/hillel/treshchun/lessons/lesson5Homework7/Occurance.java
> +            int[] counter = {0};
Тот самый effectively final счетчик. Я так и не придумал более элегантный способ посчитать кол-во срабатываний foreach с лямбда  выражением. На stackverflow рекомендуют так, либо AtomicInteger, либо использование свойства обьекта - это логично в следующем задании. Еще предлагали через peek, но это stream, тут задание без stream. Как тут лучше сделать?

2024-03-25 17:15 UTC, pipekalo approved these changes

2024-03-25 17:15 UTC, pipekalo commented on src/main/java/ua/hillel/treshchun/lessons/lesson5Homework7/Occurance.java
> +            int[] counter = {0};
можешь не замормачиваться в этом задании над этим

2024-03-25 17:15 UTC, pipekalo commented on src/main/java/ua/hillel/treshchun/lessons/lesson5Homework7/Occurance.java
> +                if (word.equals(uniqueWord)) {
можешь не замормачиваться в этом задании над этим

2024-04-03 10:28 UTC, merged